#Init TFTP-server service
---
- name: "{{ tftp_service_name }} service config on host"
  template:
    src: systemd/tftp.service.j2
    dest: "/etc/systemd/system/{{ tftp_service_name }}.service"
    backup: yes
  notify: "{{ tftp_service_name }} restart"
