#Remove TFTP-server service
---
- name: "Stop {{ tftp_service_name }}"
  service:
    name: "{{ tftp_service_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes

- name: "Remove /etc/systemd/system/{{ tftp_service_name }}.service"
  file:
    path: "/etc/systemd/system/{{ tftp_service_name }}.service"
    state: absent
  notify: "{{ tftp_service_name }} restart uninstall"
