---
- name: "{{ tftp_service_name }} restart"
  become: true
  shell: systemctl daemon-reload
  notify: "{{ tftp_service_name }} restart service"

- name: "{{ tftp_service_name }} restart service"
  become: true
  service:
    name: "{{ tftp_service_name }}"
    state: restarted
    enabled: yes
  notify: firewall-cmd add-port

- name: firewall-cmd add-port
  become: true
  shell: firewall-cmd --zone=public --permanent --add-port={{ tftp_host_port }}/{{ tftp_port_type }}
  notify: service firewalld reload  

- name: "{{ tftp_service_name }} restart uninstall"
  become: true
  shell: systemctl daemon-reload
  notify: reset-failed

- name: reset-failed
  become: true
  shell: systemctl reset-failed
  notify: firewall-cmd remove-port

- name: firewall-cmd remove-port
  become: true
  shell: firewall-cmd --zone=public --permanent --remove-port={{ tftp_host_port }}/{{ tftp_port_type }}
  notify: service firewalld reload

- name: service firewalld reload
  become: true
  shell: systemctl restart firewalld
